### ISSUE TITLE
Multiple Errors on run

### ISSUE THREAD

**Issue by Phoebe-Atkinson** [CanberraGrammar/CTF-Exercises-2017#1]
despite installing all of the prerequisites via pip, when I run
#~python3 notes.py
It outputs the following:

notes.py:2: ExtDeprecationWarning: Importing flask.ext.autodoc is deprecated, use flask_autodoc instead.
  from flask.ext.autodoc.autodoc import Autodoc
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_autodoc/__init__.py:3: ExtDeprecationWarning: Importing flask.ext.autodoc is deprecated, use flask_autodoc instead.
  from flask.ext.autodoc.autodoc import Autodoc
Traceback (most recent call last):
  File "notes.py", line 158, in <module>
    app.run(debug=True, host='0.0.0.0', port='5000')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
TypeError: an integer is required (got type str)

**Comment by moorecode** [comment]
fixed in [this](https://github.com/CanberraGrammar/CTF-Exercises-2017/commit/320a6c32df98f80890d1412c51134f561e7acf04) commit
